### PR TITLE
updated css for banner

### PR DESCRIPTION
**Pull request by NyashaNziramasanga**
Updated the CSS for wider screen sizes, and tested it on a 2560 x 1080 (Ultra Wide) screen

## Before
Screen Shot 2020-10-31 at 4 40 05 pm

## After
Screen Shot 2020-10-31 at 5 06 42 pm

### CODE REVIEW

**Comment by leerob** [comment]
This doesn't look right on desktop though, as it should take up the full width 😢

**Comment by NyashaNziramasanga** [comment]
I see what you mean, I just updated it for you

**Comment by leerob** [comment]
What's currently in production: 
image
This PR: 
image


I do agree that it doesn't look great on large screens, but I haven't found a good way to handle that. Definitely open to ideas here! 🙏

**Comment by NyashaNziramasanga** [comment]
Totally understand will close the PR for now

**Comment by leerob** [comment]
Thank you regardless, I appreciate it 🙏

**Pull request closed without merging**
